[project]
<<<<<<< HEAD
name = "resume-critique"
=======
name = "project"
>>>>>>> a8275be (updated project toml file)
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
<<<<<<< HEAD
dependencies = []
=======
dependencies = [
    "openai>=1.102.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.1.1",
    "streamlit>=1.49.1",
]
>>>>>>> a8275be (updated project toml file)
